server:
  port: 8086
spring:
  datasource:
    username: mucheng
    url: jdbc:mysql://localhost:3306/mysql
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

#   redis
redis:
  port: 6379
  password:
  cluster:
    node: localhost
  lettuce:
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 20
logging:
  level:
    com.dormitory.mapper: debug


mybatis:
    mapper-locations: classpath:mapper/*.xml


upload:
    PICT-path: E:/RuleAssets/PICT/
    graphwalker-path: E:/RuleAssets/Graphwalker/
    PICT-output-path: E:/RuleAssets/PICT/RuleTxt/
    graphwalker-output-path: E:/RuleAssets/Graphwalker/Output

txtpath:
  txtsavepath: E:/RuleAssets/PICT/RuleTxt/

address:
    webip: http://127.0.0.1:8080/